// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfxohxoizdbrdwvknnnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeG9oeG9pemRicmR3dmtubm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzQ4MTMsImV4cCI6MjA2Njk1MDgxM30.A--XxW70jVbib0EPY0mv_eL02HxZ7wu2GToSqO3Db3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});